import { createGlobalStyle } from "styled-components";
import type { NextPage } from "next";
import Head from "next/head";
import { HomeDashboard } from "../components/HomeDashboard";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";

const GlobalStyle = createGlobalStyle`
  html, body {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    overflow-x: hidden;
    overflow-y:hidden;
    background: linear-gradient(to bottom, #e0e7ff, #f8fafc);
  }

  #__next {
    height: 100%;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <GlobalStyle />
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <HomeDashboard />
      <Footer />
    </div>
  );
};

export default Home;
