// components/Layout.tsx
import React, { ReactNode } from "react";
import styled from "styled-components";

import Head from "next/head";
import { Header } from "./Header";

const Main = styled.main`
  flex: 1;
  display: flex;
  flex-direction: column;
`;

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>BAO</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <Main>{children}</Main>
    </div>
  );
};

export default Layout;
